# @package _global_

model:
  type: 'crossformer'
  retrain: true
  restart: false
ts:
  name: 'test'
  version: 1
  enrich: ['minute']
  use_covariates: true
  use_future_covariates: true
  silly: false

model_configs:
  use_classical_positional_encoder: true
  emb_dim: 7 
  reduction_mode: mean
  d_model: 4
  hidden_size: 4
  n_layer_encoder: 2
  n_head: 2
  dropout_rate: 0.5
  win_size: 2
  seg_len: 6
  factor: 1
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'
  quantiles: [0.1,0.5,0.9]

train_config:
  batch_size: 128
  max_epochs: 100
            
