# @package _global_

model:
  type: 'itransformer'
  retrain: true
  restart: false
ts:
  name: 'test'
  version: 1
  enrich: ['hour']
  use_covariates: true
  use_future_covariates: true
  silly: false
  
model_configs:
  use_classical_positional_encoder: true 
  emb_dim: 16 
  reduction_mode: mean 
  d_model: 4
  n_head: 4
  hidden_size: 64
  dropout_rate: 0.1
  n_layer_decoder: 3
  use_norm: True
  optim: torch.optim.AdamW
  persistence_weight: 0.010
  loss_type: 'l1'
  activation: torch.nn.ReLU
  class_strategy: 'projection' #projection/average/cls_token
  quantiles: [0.1,0.5,0.9]
train_config:
  batch_size: 32
  max_epochs: 1
         