# @package _global_

model:
  type: 'simple'
  retrain: true
  restart: false
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: false
  use_future_covariates: true
  silly: false

model_configs:
  use_classical_positional_encoder: true 
  emb_dim: 16 
  reduction_mode: mean 
  dropout_rate: 0.0
  hidden_size: 512
  
  optim: torch.optim.Adam
  activation: torch.nn.ReLU
  persistence_weight: 0.010
  loss_type: 'l1'
  quantiles: [] #[0.1,0.5,0.9]

train_config:
  batch_size: 64
  max_epochs: 5

              
