# @package _global_

model:
  type: 'tft'
  retrain: true
  restart: false
ts:
  name: 'test'
  version: 1
  enrich: []
  use_covariates: true
  use_future_covariates: true
  silly: false
model_configs:
  use_classical_positional_encoder: true 
  emb_dim: 16 
  reduction_mode: mean 
  d_model: 4
  d_head: 4
  n_head: 4
  num_layers_RNN: 8
  optim: torch.optim.Adam
  dropout_rate: 0.5
  persistence_weight: 0.010
  loss_type: 'l1'
  quantiles: [0.1,0.5,0.9]
train_config:
  batch_size: 128
  max_epochs: 3
            
