# @package _global_

model:
  type: 'duet'
  retrain: true
  restart: false
ts:
  name: 'test'
  version: 1
  enrich: ['hour']
  use_covariates: true
  use_future_covariates: true

model_configs:
  use_classical_positional_encoder: true
  emb_dim: 16 
  reduction_mode: mean
  factor: 1
  d_model: 16
  n_head: 1
  n_layer: 2
  CI: false
  d_ff: 16
  noisy_gating: True
  num_experts: 4
  kernel_size: 7
  hidden_size: 16
  dropout_rate: 0.1
  quantiles: []
  k: 1
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'
  activation: torch.nn.ReLU
  quantiles: [0.1,0.5,0.9]
train_config:
  batch_size: 64
  max_epochs: 2
         