# @package _global_

model:
  type: 'linear'
  retrain: true
  restart: false
ts:
  name: 'weather_d'
  version: 1
  enrich: ['hour']
  use_covariates: false
  use_future_covariates: true
  silly: false
model_configs:
  use_classical_positional_encoder: true 
  emb_dim: 17
  reduction_mode: mean 
  kernel_size: 3
  hidden_size: 12
  kind: 'dlinear'
  optim: torch.optim.SGD
  activation: torch.nn.LeakyReLU
  simple: false
  quantiles: [0.1,0.5,0.9]
train_config:
  batch_size: 256
  max_epochs: 2
                   
