# @package _global_

model:
  type: 'duet'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['hour']
  use_covariates: true


model_configs:
  factor: 1
  d_model: 16
  n_head: 1
  n_layer: 2
  CI: 1
  d_ff: 16
  noisy_gating: True
  num_experts: 4
  kernel_size: 7
  hidden_size: 16
  dropout_rate: 0.1
  quantiles: []
  k: 1
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'
  activation: torch.nn.ReLU

train_config:
  batch_size: 64
  max_epochs: 2
         