# @package _global_

model:
  type: 'patchtst'
  retrain: true
  restart: false
ts:
  name: 'test'
  version: 1
  enrich: []
  use_covariates: true
  use_future_covariates: true
  silly: false
model_configs:
  use_classical_positional_encoder: true 
  emb_dim: 16 
  reduction_mode: mean 
  d_model: 4
  kernel_size: 3
  decomposition: true
  n_layer: 2
  patch_len: 4
  n_head: 2
  stride: 4
  dropout_rate: 0.5
  hidden_size: 12
  optim: torch.optim.Adam
  activation: torch.nn.PReLU
  persistence_weight: 0.010
  loss_type: 'l1'
  remove_last: true
  quantiles: [0.1,0.5,0.9]
train_config:
  batch_size: 128
  max_epochs: 3
            
