# @package _global_

model:
  type: 'itransformer'
  retrain: true
ts:
  name: 'test_venice'
  version: 1
  enrich: ['hour']
  use_covariates: true


model_configs:
  d_model: 64
  n_head: 4
  hidden_size: 64
  dropout_rate: 0.1
  n_layer_decoder: 4
  use_norm: True
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'
  activation: torch.nn.ReLU
  class_strategy: 'projection' #projection/average/cls_token

train_config:
  batch_size: 64
  max_epochs: 20
         